# Generated by Django 2.1.3 on 2018-12-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField(blank=True, null=True)),
                ('approved', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('salary_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('dependent', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'company_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.IntegerField(primary_key=True, serialize=False)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'county',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('job_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_category', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'job_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('postal_code_id', models.IntegerField(primary_key=True, serialize=False)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'postal_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
    ]
